/** 멤버십 서비스에 필요한 기초 테이블 스크립트 **/

drop table if exists TB_MBSP;
drop table if exists TB_MY_MBSP;


/* 멤버십 정보 (TB_MBSP) */
CREATE TABLE TB_MBSP (
    MBSP_ID VARCHAR(15) NOT NULL COMMENT '멤버십ID',
    MBSP_NM VARCHAR(100) NOT NULL COMMENT '멤버십명',
    STATUS CHAR DEFAULT '1' COMMENT '상태 (1:사용, 9:정지)',
    MBSP_INFO VARCHAR(200) NOT NULL COMMENT '멤버십 안내문구',
    MBSP_IMG_URL VARCHAR(200) COMMENT '멤버십 이미지 경로',
    HOMEPAGE_URL VARCHAR(200) COMMENT '본사 홈페이지 URL',
    BIGO VARCHAR(2000) COMMENT '비고',
    INSERT_DATE TIMESTAMP COMMENT '등록일자',
    INSERT_USER BIGINT COMMENT '등록자ID',
    UPDATE_DATE TIMESTAMP COMMENT '수정일자',
    UPDATE_USER BIGINT COMMENT '수정자ID',
    CONSTRAINT TB_MBSP_PK PRIMARY KEY(MBSP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '멤버십 정보';


/* 나의 멤버십정보 (TB_MY_MBSP) */
CREATE TABLE TB_MY_MBSP (
    ACNT_ID BIGINT NOT NULL COMMENT '회원번호',
    MBSP_ID VARCHAR(15) NOT NULL COMMENT '멤버십ID',
    STATUS CHAR DEFAULT '1' COMMENT '상태 (1:사용, 0:탈퇴)',
    TOTAL_ACCUM_POINT INT Default 0 COMMENT '총 적립 포인트',
    MBSP_GRD_CD VARCHAR(10) Default 'COMMON' COMMENT '멤버십 등급코드',
    INSERT_DATE TIMESTAMP NOT NULL COMMENT '가입일자',
    WITHDRAWAL_DATE TIMESTAMP COMMENT '탈퇴일자',
    CONSTRAINT TB_MY_MBSP_PK PRIMARY KEY(ACNT_ID, MBSP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '나의 멤버십정보';
